
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Development/Qt/Tools/CMake_64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
