delete from o_body;
delete from o_header;
delete from o_goods;
delete from o_pay_cl;
delete from o_pay_room;
delete from o_payment;
delete from o_store_output;
delete from o_tax;
delete from o_tax_debug;
delete from o_tax_log;
delete from a_store;
delete from a_store_draft;
delete from a_store_inventory;
delete from a_header;
delete from s_settings_values;
delete from s_settings_names;
delete from s_user_group where f_id>1;
delete from s_user where f_id>1;
delete from s_db_access;
delete from s_db;
delete from s_user_access;
delete from b_cards_discount;
delete from b_clients;
delete from b_history;
delete from d_menu;
delete from d_menu_names;
delete from d_recipes;
delete from d_dish;
delete from d_part2;
delete from d_part1;
delete from d_printers;
delete from c_goods;
delete from c_goods_scancode;
delete from c_goods_waste;
delete from c_groups;
delete from s_deleted;
delete from s_waiter_reports;
delete from s_cache;
delete from e_cash;
delete from droid_message;
delete from d_img;
delete from o_dish_remove_reason;
delete from d_dish_comment;
delete from a_reason where f_id>7;
delete from h_tables;
delete from h_halls;
delete from c_partners;
delete from c_units;
delete from d_special;
delete from d_translator;
ALTER TABLE `d_part1` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_part2` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_dish` AUTO_INCREMENT = 0 ;
ALTER TABLE `s_settings_names` AUTO_INCREMENT = 0 ;
ALTER TABLE `s_settings_values` AUTO_INCREMENT = 0 ;
ALTER TABLE `c_goods` AUTO_INCREMENT = 0 ;
ALTER TABLE `c_goods_scancode` AUTO_INCREMENT = 0 ;
ALTER TABLE `c_goods_waste` AUTO_INCREMENT = 0 ;
ALTER TABLE `c_groups` AUTO_INCREMENT = 0 ;
ALTER TABLE `c_units` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_menu` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_menu_names` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_printers` AUTO_INCREMENT = 0 ;
ALTER TABLE `c_partners` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_dish_comment` AUTO_INCREMENT = 0 ;
ALTER TABLE `b_cards_discount` AUTO_INCREMENT = 0 ;
ALTER TABLE `b_clients` AUTO_INCREMENT = 0 ;
ALTER TABLE `b_history` AUTO_INCREMENT = 0 ;
ALTER TABLE `a_reason` AUTO_INCREMENT = 7 ;
ALTER TABLE `o_dish_remove_reason` AUTO_INCREMENT = 0 ;
ALTER TABLE `d_translator` AUTO_INCREMENT = 0 ;
ALTER TABLE `s_db` AUTO_INCREMENT = 1 ;
ALTER TABLE `s_db_access` AUTO_INCREMENT = 1 ;
ALTER TABLE `o_store_output` AUTO_INCREMENT = 0 ;
ALTER TABLE `h_halls` AUTO_INCREMENT = 0 ;
ALTER TABLE `h_tables` AUTO_INCREMENT = 0 ;
alter table d_special auto_increment=0;
delete from c_storages;
ALTER TABLE `c_storages` AUTO_INCREMENT = 0 ;
insert into d_printers (f_name) values ('');