#ifndef WAITERSERVICE_GLOBAL_H
#define WAITERSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WAITERSERVICE_LIBRARY)
#define WAITERSERVICE_EXPORT Q_DECL_EXPORT
#else
#define WAITERSERVICE_EXPORT Q_DECL_IMPORT
#endif

#endif // WAITERSERVICE_GLOBAL_H
