#!/usr/bin/env python3
"""Собрать все хранимки из engine/db/sp/*.sql в один sp.sql для прогона на сервере.

Правило:
  - правишь отдельные файлы в sp/ (удобно смотреть/диффать)
  - запускаешь этот скрипт → пересоздаётся sp.sql
  - на сервере выполняешь ТОЛЬКО sp.sql

Usage:
  python build_sp_sql.py
  mysql -uroot -p dbname < sp.sql

Windows:
  build_sp.bat
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SP_DIR = ROOT / "sp"
OUT = ROOT / "sp.sql"


def normalize_for_mysql_client(sql: str) -> str:
    """Make one source file safe for mysql CLI / HeidiSQL (DELIMITER is client-only)."""
    text = sql.strip()
    if not text:
        return ""

    has_delimiter = bool(re.search(r"(?im)^\s*DELIMITER\b", text))
    uses_dollar = "$$" in text

    if has_delimiter:
        # DROP ...; must run with default ';' BEFORE switching to $$
        # Bad source pattern: DELIMITER $$\nDROP ...;\nCREATE ...
        text = re.sub(
            r"(?is)^\s*DELIMITER\s+\$\$\s*\n\s*(DROP\s+(?:FUNCTION|PROCEDURE)\s+IF\s+EXISTS\s+[`\w]+)\s*;",
            r"\1;\nDELIMITER $$",
            text,
            count=1,
        )
        if not re.search(r"(?im)^\s*DELIMITER\s*;\s*$", text):
            text += "\nDELIMITER ;\n"
        return text.rstrip() + "\n"

    if uses_dollar:
        # Body already uses $$ terminators but no DELIMITER directives
        return f"DELIMITER $$\n{text}\nDELIMITER ;\n"

    # Plain CREATE ... END; — wrap whole body
    return f"DELIMITER $$\n{text}\n$$\nDELIMITER ;\n"


def main() -> None:
    files = sorted(SP_DIR.glob("*.sql"))
    if not files:
        raise SystemExit(f"No *.sql in {SP_DIR}")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    file_list = "\n".join(f"--   - {p.name}" for p in files)

    parts: list[str] = [
        "-- =============================================================================\n"
        "-- ALL stored procedures / functions. Run this file on the server to recreate.\n"
        "-- Do NOT edit this file by hand. Edit files in sp/, then: python build_sp_sql.py\n"
        f"-- Generated: {now}\n"
        f"-- Sources ({len(files)}):\n"
        f"{file_list}\n"
        "--\n"
        "-- Usage:\n"
        "--   mysql -uroot -p YOUR_DB < sp.sql\n"
        "--   or open sp.sql in HeidiSQL and Execute\n"
        "-- =============================================================================\n"
        "\n"
        "DELIMITER ;\n"
    ]

    for path in files:
        body = path.read_text(encoding="utf-8", errors="replace")
        if not body.strip():
            continue
        parts.append(f"\n-- ========== {path.name} ==========\n")
        parts.append(normalize_for_mysql_client(body))
        parts.append("DELIMITER ;\n")

    OUT.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    print(f"  {len(files)} files from {SP_DIR}")
    for p in files:
        print(f"  + {p.name}")


if __name__ == "__main__":
    main()
