# Reads ararix/secrets.properties and writes the gitignored Dart and iOS key files.
# Android reads secrets.properties directly from Gradle.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$secretsPath = Join-Path $root "secrets.properties"
if (-not (Test-Path $secretsPath)) {
    throw "Missing $secretsPath (copy secrets.properties.example)"
}

$key = $null
foreach ($line in Get-Content $secretsPath) {
    if ($line -match '^\s*GOOGLE_MAPS_API_KEY\s*=\s*(.*)\s*$') {
        $key = $Matches[1].Trim()
    }
}
if ([string]::IsNullOrWhiteSpace($key)) {
    throw "GOOGLE_MAPS_API_KEY is empty in secrets.properties"
}

$dartPath = Join-Path $root "lib\features\address\data\maps_key.dart"
$dart = @"
// Generated by tool/sync_maps_secrets.ps1. Gitignored. Do not commit.
const String mapsApiKey = '$key';
"@
[IO.File]::WriteAllText($dartPath, $dart.Replace("`r`n", "`n"))

$xcPath = Join-Path $root "ios\Flutter\MapsSecrets.xcconfig"
$xc = "GOOGLE_MAPS_API_KEY=$key`n"
[IO.File]::WriteAllText($xcPath, $xc)

Write-Host "Updated maps_key.dart and ios/Flutter/MapsSecrets.xcconfig"
