delete from a_dc;
delete from a_header_cash;
delete from a_header_store;
delete from a_complectation_additions;
delete from a_header_shop2partner;
delete from a_header_shop2partneraccept;
delete from a_store_reserve;
delete from a_store_sale;
delete from a_store_temp;
delete from o_body;
delete from o_header_flags;
delete from o_header;
delete from o_goods;
delete from o_pay_cl;
delete from o_pay_room;
delete from o_payment;
delete from o_tax;
delete from o_header_options;
delete from o_preorder;
delete from o_tax_debug;
delete from o_tax_log;
delete FROM o_waiterserver_debug;
delete from a_complectation_additions;
delete from s_login_session;
delete from a_store;
delete from a_store_draft;
delete from e_cash;
delete from a_store_inventory;
delete from o_package;
delete from op_body;
delete from op_header;
delete from a_header;
delete from s_settings_values;
delete from s_settings_names;
delete from s_user_photo;
delete from s_user_access;
delete from s_user where f_id>1;
delete from s_user_group where f_id>1;
delete from s_db_access where f_id>1;
delete from s_db;
delete from b_car;
delete from b_cards_discount;
delete from b_history;
delete from d_menu;
delete from d_menu_names;
delete from d_recipes;
delete from d_dish;
delete from d_part2;
delete from c_goods_option;
delete from c_goods_multiscancode;
delete from d_part1;
delete from d_printers;
delete from c_goods_images;
delete from c_goods_complectation;
delete from c_goods_classes;
delete from c_goods;
delete from c_goods_waste;
delete from c_groups;
delete from s_waiter_reports;
delete from s_cache;
delete from droid_message;
delete from d_image;
delete from d_print_aliases;
delete from a_store_sale;
delete from o_dish_remove_reason;
delete from d_dish_comment;
delete from a_reason where f_id>9;
delete from h_tables;
delete from h_halls;
delete from c_partners;
delete from c_units;
delete from d_special;
delete from d_translator;
delete from d_package;
delete from d_package_list;
delete from d_stoplist;
delete from s_salary_body;
delete from s_salary_options;
delete from s_syncronize;
delete from s_draft;
delete from e_cash_names;
delete from a_store_sale;

delete from mf_daily_workers;
delete from mf_daily_process;
delete from mf_process;
delete from mf_actions;
delete from mf_actions_group;

delete from c_storages;
alter table a_store_sale auto_increment=0;
alter table a_store_reserve auto_increment=0;
alter table c_goods_classes auto_increment = 0;
alter table s_login_session auto_increment=0;
ALTER TABLE d_part1 AUTO_INCREMENT = 0 ;
ALTER TABLE d_part2 AUTO_INCREMENT = 0 ;
alter table c_goods_option auto_increment = 0;

ALTER TABLE s_syncronize AUTO_INCREMENT = 0 ;
ALTER TABLE d_package AUTO_INCREMENT = 0 ;
alter table d_print_aliases auto_increment=0;
alter table c_goods_images auto_increment=0;
ALTER TABLE d_package_list AUTO_INCREMENT = 0 ;
ALTER TABLE d_dish AUTO_INCREMENT = 0 ;
alter table e_cash_names auto_increment=0;
ALTER TABLE s_settings_names AUTO_INCREMENT = 0 ;
ALTER TABLE s_settings_values AUTO_INCREMENT = 0 ;
ALTER TABLE c_goods AUTO_INCREMENT = 0 ;
ALTER TABLE o_package AUTO_INCREMENT = 0 ;
alter table s_user_photo auto_increment=0;
ALTER TABLE c_goods_waste AUTO_INCREMENT = 0 ;
ALTER TABLE c_groups AUTO_INCREMENT = 0 ;
ALTER TABLE c_goods_complectation AUTO_INCREMENT = 0 ;
ALTER TABLE c_units AUTO_INCREMENT = 3 ;
ALTER TABLE d_menu AUTO_INCREMENT = 0 ;
ALTER TABLE d_image AUTO_INCREMENT = 0 ;
ALTER TABLE d_menu_names AUTO_INCREMENT = 0 ;
ALTER TABLE d_printers AUTO_INCREMENT = 0 ;
ALTER TABLE c_partners AUTO_INCREMENT = 0 ;
ALTER TABLE d_dish_comment AUTO_INCREMENT = 0 ;
ALTER TABLE b_cards_discount AUTO_INCREMENT = 0 ;
ALTER TABLE b_history AUTO_INCREMENT = 0 ;
ALTER TABLE a_reason AUTO_INCREMENT = 7 ;
ALTER TABLE o_dish_remove_reason AUTO_INCREMENT = 0 ;
ALTER TABLE d_translator AUTO_INCREMENT = 0 ;
ALTER TABLE s_db AUTO_INCREMENT = 1 ;
ALTER TABLE s_db_access AUTO_INCREMENT = 1 ;
ALTER TABLE h_halls AUTO_INCREMENT = 0 ;
ALTER TABLE h_tables AUTO_INCREMENT = 0 ;

ALTER TABLE mf_daily_workers AUTO_INCREMENT = 0 ;
ALTER TABLE mf_daily_process AUTO_INCREMENT = 0 ;
ALTER TABLE mf_process AUTO_INCREMENT = 0 ;
ALTER TABLE mf_actions AUTO_INCREMENT = 0 ;
ALTER TABLE mf_actions_group AUTO_INCREMENT = 0 ;

ALTER TABLE a_store_sale AUTO_INCREMENT = 0 ;
alter table d_special auto_increment=0;
ALTER TABLE c_storages AUTO_INCREMENT = 0 ;
insert into d_printers (f_name) values ('');
insert into s_db (f_id, f_name, f_description, f_host, f_db, f_user, f_password) values (1, 'DB Name', 'Db Description', '127.0.0.1', 'cafe5', 'root', 'root5');
insert into c_units (f_id, f_name, f_fullname) values (1, 'Հատ', 'Հատ'), (2, 'Կգ', 'Կիլոգրամ'), (3, 'Լ', 'Լիտր');
