#ifndef C5BROADCASTING_H
#define C5BROADCASTING_H

#define WHAT_GETSERVER 1
#define WHAT_GETDOCS 2
#define WHAT_PARSE_STORE_STRING 3
#define WHAT_STORE_APPEND_ITEM 4
#define WHAT_PARSE_STORE_QTY 5
#define WHAT_PARSE_STORE_PRICE 6
#define WHAT_PARSE_STORE_AMOUNT 7

#define ACCEPT_REJECT 0
#define ACCEPT_ACCEPT 1

#endif // C5BROADCASTING_H
