#ifndef CHATMESSAGE_H
#define CHATMESSAGE_H

#define MSG_GOODS_RESERVE 1
#define MSG_PRINT_TAX 2
#define MSG_UPDATE_TEMP_STORE 3
#define MSG_ONLINE_SALE 4
#define MSG_PRINT_RECEIPT 5

#endif // CHATMESSAGE_H
