[mysqld]
basedir="__PICASSO_ROOT__/mysql"
datadir="__PICASSO_ROOT__/mysql/data"
port=3306
bind-address=127.0.0.1
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
plugin-dir="__PICASSO_ROOT__/mysql/lib/plugin"
[client]
port=3306
