# -*- coding: utf-8 -*-
"""Part 2 of professional RU translations for FrontDesk."""
T = {
"Are you sure to close application?": "Закрыть приложение?",
"Dashboard": "Панель управления",
"Password changed": "Пароль изменён",
"Favorites": "Избранное",
"New store inventory": "Новая инвентаризация",
"Goods reservations": "Резервы товаров",
"New retail traid": "Новая розничная продажа",
"New whosale traid": "Новая оптовая продажа",
"Debts journal": "Журнал долгов",
"Storage movement, uncomplected": "Перемещение без комплектации",
"Sales by goods": "Продажи по товарам",
"New cash document": "Новый кассовый документ",
"Currency rates": "Курсы валют",
"Currency cross rates": "Кросс-курсы валют",
"Currency cross rates history": "История кросс-курсов",
"History": "История",
"Payments": "Платежи",
"Dish depts": "Отделы блюд",
"Groups of goods": "Группы товаров",
"Special prices": "Специальные цены",
"Active tasks": "Активные задания",
"Workshops": "Цеха",
"Action stages": "Этапы действий",
"Products": "Изделия",
"Store reason": "Причина склада",
"Route report": "Отчёт по маршрутам",
"Positions of employees": "Должности сотрудников",
"Employees": "Сотрудники",
"Translator": "Переводчик",
"Add to favorites?": "Добавить в избранное?",
"Remove from favorites?": "Удалить из избранного?",
"Updater not found. Please download the update from the link.": "Модуль обновления не найден. Скачайте обновление по ссылке.",
"Chage password": "Сменить пароль",
"Waiter password": "Пароль официанта",
"For remove password leave this field empty": "Чтобы удалить пароль, оставьте поле пустым",
"Front desk password": "Пароль FrontDesk",
"Fingerprint": "Отпечаток пальца",
"Progress": "Прогресс",
"Global search": "Глобальный поиск",
"Revenue cash operation": "Кассовая операция выручки",
"Operation": "Операция",
"Income": "Приход",
"Outcome": "Расход",
"Operation type": "Тип операции",
"Cashbox": "Касса",
"Payment type": "Тип оплаты",
"DateTime": "Дата и время",
"Debt Recovery": "Взыскание долга",
"Sales Revenue": "Выручка от продаж",
"Cash Overage": "Излишек кассы",
"Total Expenses": "Всего расходов",
"Purchasing Costs": "Закупочные расходы",
"Salaries and Wages": "Зарплата и выплаты",
"Debt Repayment": "Погашение долга",
"Utilities": "Коммунальные услуги",
"Cash Shortage": "Недостача кассы",
"Cashbox must be selected in filter": "В фильтре нужно выбрать кассу",
"Comment is required": "Комментарий обязателен",
"filter": "фильтр",
"Driver": "Водитель",
"Partner status": "Статус контрагента",
"Route id": "ID маршрута",
"PartnerId": "ID контрагента",
"Taxname": "Налоговое наименование",
"Salary accrual": "Начисление зарплаты",
"Add employee": "Добавить сотрудника",
"Remove employee": "Удалить сотрудника",
"Change position": "Изменить должность",
"Autofill": "Автозаполнение",
"Fill from registered employees with attendance on this date": "Заполнить из сотрудников с явкой на эту дату",
"Total accrued:": "Всего начислено:",
"Position": "Должность",
"Load document for the selected date? Current rows will be replaced.": "Загрузить документ за выбранную дату? Текущие строки будут заменены.",
"Calculate": "Рассчитать",
"Print": "Печать",
"Replace current rows with employees from attendance?": "Заменить текущие строки сотрудниками из явки?",
"No registered employees with attendance on this date.": "Нет сотрудников с явкой на эту дату.",
"Employee is not set.": "Сотрудник не указан.",
"Position is not set.": "Должность не указана.",
"Add employees first.": "Сначала добавьте сотрудников.",
"Nothing to save.": "Нечего сохранять.",
"%n row(s): amount is zero.": "%n стр.: сумма равна нулю.",
"%n row(s): employee is not set.": "%n стр.: сотрудник не указан.",
"Add at least one employee with amounts.": "Добавьте хотя бы одного сотрудника с суммами.",
"Fixed": "Фиксированная",
"Dish sales base": "База продаж блюд",
"Calculated": "Расчётная",
"Bonus": "Бонус",
"Date: %1": "Дата: %1",
"Total accrued: %1": "Всего начислено: %1",
"Salary payment": "Выплата зарплаты",
"Total paid:": "Всего выплачено:",
"Fill the payment document with employees from salary accrual for today?": "Заполнить документ выплаты сотрудниками из начисления за сегодня?",
"No salary accrual entries found for this date.": "Начислений зарплаты за эту дату не найдено.",
"Debt": "Долг",
"Paid amount": "Выплаченная сумма",
"Total paid: %1": "Всего выплачено: %1",
"Sale": "Продажа",
"Order id": "ID заказа",
"Partner": "Контрагент",
"Seller": "Продавец",
"Time": "Время",
"Hall": "Зал",
"TaxDept": "Налоговый отдел",
"Print A4": "Печать A4",
"Print tax": "Печать фискального чека",
"Amount, total": "Сумма, итого",
"Amount, cash": "Сумма, наличные",
"Amount, card": "Сумма, карта",
"Excel": "Excel",
"No such order": "Заказ не найден",
"Removal complete": "Удаление выполнено",
"Date is not valid": "Некорректная дата",
"Dept option is selected, but no partner selected": "Выбран режим долга, но контрагент не выбран",
"Order": "Заказ",
"Buyer": "Покупатель",
"Material code": "Код материала",
"Total amount": "Общая сумма",
"Debug mode": "Режим отладки",
"Movement document counter*": "Счётчик документов перемещения*",
"Sale, common": "Продажа, общий",
"Auto date of close": "Автодата закрытия",
"Close table after service print": "Закрывать стол после сервисной печати",
"Close table after precheck": "Закрывать стол после пречека",
"Deny change qty": "Запретить изменение кол-ва",
"Disable grouping when printing": "Отключить группировку при печати",
"CAS program path": "Путь к программе CAS",
"Dont check qty of store": "Не проверять остаток на складе",
"Applicatin font base size": "Базовый размер шрифта приложения",
"Application font family": "Шрифт приложения",
"Update temp storage for shop": "Обновлять временный склад для магазина",
"Automatically store output after sale": "Автоматический расход со склада после продажи",
"Final receipt quantity selection": "Выбор количества на финальном чеке",
"Ask for precheck": "Запрашивать пречек",
"System thouthand separator": "Разделитель тысяч",
"Compact dishes in order": "Компактный список блюд в заказе",
"Dont close empty order": "Не закрывать пустой заказ",
"Autocharge item after close session": "Автоначисление позиции после закрытия смены",
"Hide quantity column": "Скрыть столбец количества",
"Mobile client config text": "Текст конфигурации мобильного клиента",
"External tax": "Внешний фискальный",
"Never offer tax": "Никогда не предлагать фискальный чек",
"Service print font size": "Размер шрифта сервисной печати",
"Service print font family": "Шрифт сервисной печати",
"Dont print": "Не печатать",
"Receipt print font family": "Шрифт печати чека",
"Force use print alias": "Принудительно использовать псевдоним печати",
"Receipt print font size": "Размер шрифта печати чека",
"Print modicators on receipt": "Печатать модификаторы на чеке",
"External integration": "Внешняя интеграция",
"Idram server": "Сервер Idram",
"External scale": "Внешние весы",
"Find": "Найти",
"Idram ID": "ID Idram",
"Idram phone": "Телефон Idram",
"Idram tips": "Чаевые Idram",
"Idram wallet": "Кошелёк Idram",
"Idram name": "Имя Idram",
"Idram session ID": "ID сессии Idram",
"Date of close": "Дата закрытия",
"Card autoinput": "Автоввод карты",
"Auto cash input": "Автоввод наличных",
"User id for hotel voucher": "ID пользователя для гостиничного ваучера",
"Hall id for hotel record": "ID зала для гостиничной записи",
"Mobile application connection string": "Строка подключения мобильного приложения",
"Default currency": "Валюта по умолчанию",
"No invoice record for hotel": "Нет записи счёта для гостиницы",
"Input quantity before append dish": "Вводить кол-во перед добавлением блюда",
"Company name": "Название компании",
"Company info for documents": "Реквизиты компании для документов",
"Autodiscount": "Автоскидка",
"Delivery costumer id": "ID клиента доставки",
"Debtholder filter id": "ID фильтра должников",
"Available stores": "Доступные склады",
"Coin cashdesk": "Монетная касса",
"VAT included": "НДС включён",
"Choose pos": "Выбор кассы",
"Hide revenue": "Скрыть выручку",
"Prepaid only by gift": "Предоплата только подарочной картой",
"Show whosale price": "Показывать оптовую цену",
"Bank account number": "Номер банковского счёта",
"Bank name": "Название банка",
"Company tin": "ИНН компании",
"Company address": "Адрес компании",
"Remind about out of stock": "Напоминать об отсутствии на складе",
"Service item code": "Код сервисной позиции",
"Discount item code": "Код позиции скидки",
"Waiter server": "Сервер официанта",
"Change qty of return items": "Изменять кол-во при возврате",
"Print total quantity of goods": "Печатать общее кол-во товаров",
"Clear sale draft": "Очистить черновик продажи",
"Copy from": "Копировать из",
"Full": "Полный",
"Change draft date to current": "Менять дату черновика на текущую",
"Autodiscount card   number": "Номер карты автоскидки",
"Max days of history": "Макс. дней истории",
"Sale, smart": "Продажа, смарт",
"Նկարներ": "Изображения",
"Simple fiscal": "Простой фискальный",
"Static QR code text": "Текст статического QR-кода",
"Dont print final receipt": "Не печатать финальный чек",
"Http server": "HTTP-сервер",
"HTTP server ip": "IP HTTP-сервера",
"HTTP server port": "Порт HTTP-сервера",
"HTTP server username": "Пользователь HTTP-сервера",
"HTTP server password": "Пароль HTTP-сервера",
"Connection string": "Строка подключения",
"Test": "Тест",
"Mobile": "Мобильный",
"Picasso.store buttons": "Кнопки Picasso.store",
"Orders": "Заказы",
"Loading goods": "Загрузка товаров",
"Use websocket": "Использовать WebSocket",
"Completed orders": "Завершённые заказы",
"Debts": "Долги",
"Draft sale": "Черновик продажи",
"Check quantity": "Проверять количество",
"New order": "Новый заказ",
"Store input check": "Проверка прихода",
"Sale output confirmation": "Подтверждение расхода при продаже",
"Return of goods": "Возврат товаров",
"Chat operator user id": "ID оператора чата",
"Deny logout": "Запретить выход",
"Cash autoinput": "Автоввод наличных",
"Print dish timeorder": "Печать времени блюда",
"Print scancode with name": "Печатать штрихкод с названием",
"Widthe of printer": "Ширина принтера",
"Card autoinput prefix": "Префикс автоввода карты",
"Cash autoinput prefix": "Префикс автоввода наличных",
"Receipt footer text": "Текст внизу чека",
"Sale, waiter": "Продажа, официант",
"Login after payment": "Вход после оплаты",
"Working date change time": "Время смены рабочей даты",
"Car mode": "Режим авто",
"Deny retail": "Запретить розницу",
"Deny whosale": "Запретить опт",
"Deny price changing": "Запретить изменение цены",
"Fix staff": "Фиксировать персонал",
"Printing": "Печать",
"Receipt paper width": "Ширина чековой ленты",
"Printing goods qty side": "Сторона печати кол-ва товаров",
"Left of name": "Слева от названия",
"Down of name": "Под названием",
"Tax options": "Параметры фискализации",
"Always offer tax": "Всегда предлагать фискальный чек",
"Output document counter*": "Счётчик документов расхода*",
"Input document number digits": "Знаков в номере документа прихода",
"Input documents counter*": "Счётчик документов прихода*",
"Default store": "Склад по умолчанию",
"*This settings common for all cases": "*Эти настройки общие для всех конфигураций",
"Frontdesk mode": "Режим FrontDesk",
"Movement document number digits": "Знаков в номере документа перемещения",
"Output document number digits": "Знаков в номере документа расхода",
"No cash doc option in store doc": "Без кассового документа в складском",
"No scancode in store doc": "Без штрихкода в складском документе",
"Item code for hotel voucher": "Код позиции для гостиничного ваучера",
"Service value": "Сервисный сбор",
"Main menu": "Главное меню",
"Hotel database": "База гостиницы",
"Order number prefix": "Префикс номера заказа",
"Default hall": "Зал по умолчанию",
"Default table": "Стол по умолчанию",
"Receipt printer": "Принтер чеков",
"Loading": "Загрузка",
"Saving": "Сохранение",
"S/R quantities": "Кол-ва S/R",
"Rec id": "ID записи",
"SR id": "ID S/R",
"SR name": "Название S/R",
"SR qty": "Кол-во S/R",
"Goods qty": "Кол-во товара",
"Link": "Связь",
"Sizes": "Размеры",
"Barcode print": "Печать штрихкодов",
"scancodes": "штрихкоды",
"scancodes 2": "штрихкоды 2",
"descriptions": "описания",
"Set list": "Список наборов",
"Range": "Диапазон",
"End": "Конец",
"Output store": "Склад расхода",
"Input store": "Склад прихода",
"Number": "Номер",
"Complectation": "Комплектация",
"Select": "Выбрать",
"Add": "Добавить",
"Base qty": "Базовое кол-во",
"Draft": "Черновик",
"New": "Новый",
"document": "документ",
"Complectation goods not selected": "Товары комплектации не выбраны",
"Complectation qty required": "Укажите количество комплектации",
"Empty document": "Пустой документ",
"Output store not selected": "Склад расхода не выбран",
"Input store not selected": "Склад прихода не выбран",
"Quantity not valid on row #": "Некорректное количество в строке №",
"Confirm to remove document": "Подтвердите удаление документа",
"Deleted": "Удалён",
"Doc number": "Номер документа",
"Quantity": "Количество",
"Output goods": "Товары расхода",
"Disassembly": "Разукомплектация",
"Output store is not defined": "Склад расхода не задан",
"Input store is not defined": "Склад прихода не задан",
"has no quantity": "нет количества",
"Multiple rows in result, getting first": "Несколько строк в результате, берём первую",
"WebSocket is not initialized. Restart the application.": "WebSocket не инициализирован. Перезапустите приложение.",
"No connection to the server. Check the network and try again.": "Нет связи с сервером. Проверьте сеть и повторите.",
"Failed to send the barcode request. Check the connection to the server.": "Не удалось отправить запрос штрихкода. Проверьте связь с сервером.",
"Select complect": "Выберите комплект",
"Print template": "Шаблон печати",
"Print one document": "Печать одного документа",
"Print two document": "Печать двух документов",
"Goods list": "Список товаров",
"New row": "Новая строка",
"Remove row": "Удалить строку",
"Edit goods on selected row": "Изменить товар в выбранной строке",
"New goods": "Новый товар",
"Search by scancode (F2)": "Поиск по штрихкоду (F2)",
"Leave focus": "Снять фокус",
"Search in document": "Поиск в документе",
"Goods Id": "ID товара",
"Valid date": "Срок годности",
"Remain": "Остаток",
"Addtitional costs": "Доп. расходы",
"Responsible persons": "Ответственные",
"Accepted": "Принял",
"Passed": "Сдал",
"Write-off": "Списание",
"Doc. number": "Номер док.",
"Sum": "Сумма",
"Doc type": "Тип документа",
"Partial paid": "Частично оплачено",
"Payment settings": "Настройки оплаты",
"Total qty": "Всего кол-во",
"Save comment without making draft": "Сохранить комментарий без перевода в черновик",
"Export": "Экспорт",
"to Excel": "в Excel",
"barcode": "штрихкод",
"Duplicate as output": "Дублировать как расход",
"Duplicate as input": "Дублировать как приход",
"Partner not selected": "Контрагент не выбран",
"Armenian dram": "Армянский драм",
"Import": "Импорт",
"from XML": "из XML",
"warning": "предупреждение",
"Price difference for %1 is more than %2%. Current: %3, Old: %4. Accept?": "Разница цены для %1 больше %2%. Текущая: %3, прежняя: %4. Принять?",
"Document has unsaved changes. Save before closing?": "В документе есть несохранённые изменения. Сохранить перед закрытием?",
"Close without saving": "Закрыть без сохранения",
"Significant price difference for ": "Существенная разница цены для ",
" on row ": " в строке ",
"Price not valid on row #": "Некорректная цена в строке №",
"Partner not specified": "Контрагент не указан",
"Row #": "Строка №",
" empty qty": " пустое кол-во",
"Payment type not specified": "Тип оплаты не указан",
"Paid amount is not valid": "Сумма оплаты некорректна",
"Paid amount cannot exceed document total": "Сумма оплаты не может превышать итог документа",
"Cashbox not selected": "Касса не выбрана",
"Cannot add goods without code": "Нельзя добавить товар без кода",
"Cannot change goods without code": "Нельзя изменить товар без кода",
"Imported from inventory surplus ": "Импортировано из излишка инвентаризации ",
"Unsupported document type": "Неподдерживаемый тип документа",
"Import is available only for draft documents": "Импорт доступен только для черновиков",
"Import from XML": "Импорт из XML",
"No invoices found in XML file": "В XML-файле не найдено накладных",
"Import cancelled: invoice %1 already exists in the database.": "Импорт отменён: накладная %1 уже есть в базе.",
"Preparing…": "Подготовка…",
"Checking %1 (%2 / %3)": "Проверка %1 (%2 / %3)",
"Importing invoices…": "Импорт накладных…",
"Importing %1 (%2 / %3)": "Импорт %1 (%2 / %3)",
"%1 — import failed": "%1 — ошибка импорта",
"%1 — save failed": "%1 — ошибка сохранения",
"Store input XML import — errors": "Импорт прихода из XML — ошибки",
"Saved: %1 / %2": "Сохранено: %1 / %2",
"Partner with TIN %1 was not found. Import aborted for invoice %2.": "Контрагент с ИНН %1 не найден. Импорт накладной %2 прерван.",
"Unknown error": "Неизвестная ошибка",
"Empty document id": "Пустой ID документа",
"Store input XML import — delete errors": "Импорт прихода из XML — ошибки удаления",
"Failed to write delete errors:": "Не удалось записать ошибки удаления:",
"Failed to import invoice %1 into a new document": "Не удалось импортировать накладную %1 в новый документ",
"Document already contains goods lines. Replace existing lines?": "В документе уже есть строки товаров. Заменить существующие строки?",
"Replace": "Заменить",
"Partner with TIN %1 was not found. Create from invoice data?": "Контрагент с ИНН %1 не найден. Создать по данным накладной?",
"Cannot load goods data for: %1": "Не удалось загрузить данные товара: %1",
"Imported %1 goods lines from invoice %2": "Импортировано %1 строк товаров из накладной %2",
"Не оплачено": "Не оплачено",
"Filter by name": "Фильтр по названию",
"Diff": "Разница",
"Export diffs": "Экспорт расхождений",
"Store inventorization": "Инвентаризация склада",
"Select storage": "Выберите склад",
"This action will clear current result": "Это действие очистит текущий результат",
"Cannot save an emtpy document": "Нельзя сохранить пустой документ",
"Stores must be different": "Склады должны отличаться",
"Imported from inventory deficit ": "Импортировано из недостачи инвентаризации ",
"Failed to reload dictionary from server.": "Не удалось перезагрузить справочник с сервера.",
"Server error while loading the list.": "Ошибка сервера при загрузке списка.",
"Failed to send the search request. Check the connection to the server.": "Не удалось отправить поисковый запрос. Проверьте связь с сервером.",
}
