# -*- coding: utf-8 -*-
"""Part 1 of professional RU translations for FrontDesk."""
T = {
"ArmSoft export options": "Параметры экспорта ArmSoft",
"Service": "Услуга",
"Expcense account": "Счёт расхода",
"Income account": "Счёт прихода",
"Materials": "Материалы",
"Expense account": "Счёт расхода",
"VAT type": "Тип НДС",
"Barista": "Бариста",
"OK": "ОК",
"Cancel": "Отмена",
"Code": "Код",
"Group": "Группа",
"Name": "Наименование",
"Part": "Часть",
"Full caption": "Полное название",
"Unit": "Ед. изм.",
"Scancode": "Штрихкод",
"Complect output": "Выход комплекта",
"Qty in box": "Кол-во в коробке",
"Retail price": "Розничная цена",
"Whosale price": "Оптовая цена",
"Adg code": "Код АДГ",
"Address": "Адрес",
"Legal name": "Юридическое название",
"Contact": "Контакт",
"Info": "Информация",
"Phone": "Телефон",
"Email": "Эл. почта",
"Taxcode": "ИНН",
"Teamlead": "Бригадир",
"Description": "Описание",
"Currency code": "Код валюты",
"Row": "Строка",
"Product code": "Код изделия",
"Product": "Изделие",
"Process code": "Код процесса",
"Process": "Процесс",
"Duration": "Длительность",
"Rate": "Курс",
"Symbol": "Символ",
"Currency code1": "Код валюты 1",
"Currency name 1": "Название валюты 1",
"Currency code 2": "Код валюты 2",
"Currency name 2": "Название валюты 2",
"Date": "Дата",
"Status": "Статус",
"Price": "Цена",
"Type": "Тип",
"Form": "Форма",
"Currency": "Валюта",
"Cash name": "Название кассы",
"Cash movement": "Движение по кассе",
"Source cashbox": "Касса-источник",
"Destination cashbox": "Касса-получатель",
"Comment": "Комментарий",
"Select source cashbox to load available funds": "Выберите кассу-источник, чтобы загрузить доступные средства",
"Save": "Сохранить",
"No available funds in this cashbox": "В этой кассе нет доступных средств",
"Enter amount to move or click Available to fill": "Введите сумму перевода или нажмите «Доступно»",
"Funds": "Средства",
"Amount": "Сумма",
"Available": "Доступно",
"Click to fill amount": "Нажмите, чтобы заполнить сумму",
"Source cashbox is required": "Укажите кассу-источник",
"Destination cashbox is required": "Укажите кассу-получатель",
"Source and destination must differ": "Касса-источник и касса-получатель должны отличаться",
"Amount exceeds available funds": "Сумма превышает доступные средства",
"Amount must be greater than zero": "Сумма должна быть больше нуля",
"Change input price": "Изменить цену прихода",
"Goods": "Товары",
"Change": "Изменить",
"This record not exists": "Запись не существует",
"Goods is not selected": "Товар не выбран",
"Change password": "Сменить пароль",
"Old password": "Старый пароль",
"New password": "Новый пароль",
"Confirm password": "Подтвердите пароль",
"Password does not match": "Пароли не совпадают",
"Password cannot be empty": "Пароль не может быть пустым",
"Old password doesnt match": "Старый пароль неверный",
"Price for group": "Цена для группы",
"Wholesale price": "Оптовая цена",
"Check code": "Код проверки",
"Retail discounted": "Розница со скидкой",
"Wholesale discounted": "Опт со скидкой",
"Check code is not valid": "Код проверки неверный",
"Empty report": "Пустой отчёт",
"Selector name": "Название селектора",
"Connection": "Подключение",
"Connection  type": "Тип подключения",
"Server username": "Имя пользователя сервера",
"Settings name": "Имя настроек",
"Server key": "Ключ сервера",
"Authenticate on the server": "Аутентификация на сервере",
"Settings password": "Пароль настроек",
"None  secure": "Без защиты",
"Secure connection (SSL)": "Защищённое соединение (SSL)",
"Server address": "Адрес сервера",
"Server password": "Пароль сервера",
"Access denied": "Доступ запрещён",
"Saved": "Сохранено",
"Filter": "Фильтр",
"Nothing was selected": "Ничего не выбрано",
"Data synchronization": "Синхронизация данных",
"Revert": "Отменить",
"Query": "Запрос",
"Done": "Готово",
"Date range": "Период",
"Date start": "Дата начала",
"Date end": "Дата окончания",
"Reset option": "Параметр сброса",
"Select option to reset": "Выберите параметр для сброса",
"Reset sales and buy information": "Сброс данных продаж и закупок",
"SALE CODE": "КОД ПРОДАЖ",
"Full reset": "Полный сброс",
"FULL CODE": "ПОЛНЫЙ КОД",
"Accept": "Принять",
"Select atleast one option": "Выберите хотя бы один параметр",
"Checking code for sales and buy not correct": "Код проверки продаж и закупок неверный",
"Checking code for full reset not correct": "Код проверки полного сброса неверный",
"User": "Пользователь",
"New Row": "Новая строка",
"New Column": "Новый столбец",
"Database access": "Доступ к базе данных",
"Login": "Вход",
"Updater not found. Reinstall the application.": "Модуль обновления не найден. Переустановите приложение.",
"Reedem accumulated": "Списать накопленное",
"Amount to reedem": "Сумма к списанию",
"Redeem": "Списать",
"Delete record": "Удалить запись",
"Customer": "Клиент",
"Card": "Карта",
"Transaction": "Операция",
"Current balance": "Текущий баланс",
"Partner must be selected": "Выберите контрагента",
"Amount must be greater then zero": "Сумма должна быть больше нуля",
"Invalid card id": "Неверный ID карты",
"Confirm delete record": "Подтвердите удаление записи",
"Group action": "Групповое действие",
"Store": "Склад",
"State": "Состояние",
"Start": "Старт",
"Search price in past, if not exists": "Искать цену в прошлом, если нет текущей",
"Search": "Поиск",
"Goods code": "Код товара",
"Group name": "Название группы",
"Goods name": "Название товара",
"Calculation of the cost of dishes": "Расчёт себестоимости блюд",
"The prices was updated": "Цены обновлены",
"Main": "Основное",
"Barcode": "Штрихкод",
"Emark required": "Требуется маркировка",
"Menu": "Меню",
"Menu record": "Запись меню",
"Menu code": "Код меню",
"Menu name": "Название меню",
"Print1": "Печать1",
"Print2": "Печать2",
"Recent": "Недавние",
"Additional": "Дополнительно",
"Can discount": "Разрешить скидку",
"Special dicount": "Специальная скидка",
"Cooking time": "Время приготовления",
"Վերահաշվարկել": "Пересчитать",
"Daily qty": "Дневное кол-во",
"Set": "Набор",
"Dish code": "Код блюда",
"Dish name": "Название блюда",
"Մաքսիմալ քանակ": "Макс. количество",
"Ready dish weight": "Вес готового блюда",
"Same as in store": "Как на складе",
"Image": "Изображение",
"Hourly payment": "Почасовая оплата",
"Extra": "Доплата",
"Add goods (+)": "Добавить товар (+)",
"New goods (Control + N)": "Новый товар (Ctrl+N)",
"Remove selected row (-)": "Удалить строку (-)",
"Copy recipe (Control + C)": "Копировать рецепт (Ctrl+C)",
"Paste recipe (Control + P)": "Вставить рецепт (Ctrl+P)",
"Comments": "Комментарии",
"Append service fee": "Добавить сервисный сбор",
"Queue": "Очередь",
"Reminder": "Напоминание",
"Color": "Цвет",
"Show online": "Показывать онлайн",
"Recipe": "Рецепт",
"Recipes": "Рецепты",
"Record": "Запись",
"Qty": "Кол-во",
"Total": "Итого",
"Dish": "Блюдо",
"Image, right click to begin": "Изображение — ПКМ для начала",
"Storage is not defined in menu.<br>": "Склад не задан в меню.<br>",
"Background color": "Цвет фона",
"You should to save dish before upload an image": "Сначала сохраните блюдо, затем загрузите изображение",
"Could not load image": "Не удалось загрузить изображение",
"Remove image": "Удалить изображение",
"Ready weight must be greater than  0": "Вес готового блюда должен быть больше 0",
"No changes": "Нет изменений",
"Confirm to remove dish comment": "Подтвердите удаление комментария к блюду",
"No recipe in clipboard": "В буфере нет рецепта",
"Could not add goods without code": "Нельзя добавить товар без кода",
"Upload image": "Загрузить изображение",
"No barcode defined.": "Штрихкод не задан.",
"Name must be defined.": "Укажите наименование.",
"Goods group must be defined": "Укажите группу товара",
"Templates of queries": "Шаблоны запросов",
"Cash doc": "Кассовый документ",
"Dialog": "Диалог",
"Save and new": "Сохранить и новый",
"Copy": "Копировать",
"Close": "Закрыть",
"Check/Uncheck all": "Отметить/снять все",
"Check/Uncheck selected": "Отметить/снять выбранные",
"Request cancel": "Отмена запроса",
"Refresh": "Обновить",
"Fiscal": "Фискальный",
"Request": "Запрос",
"Response": "Ответ",
"Confirm fiscal return": "Подтвердите фискальный возврат",
"Config fiscal machine select not implemented": "Выбор фискального аппарата не реализован",
"Taxback complete": "Фискальный возврат выполнен",
"Group id": "ID группы",
"Sold": "Продано",
"Stock": "Остаток",
"Percent %": "Процент %",
"Retail": "Розница",
"Whosale": "Опт",
"Retaile discounted": "Розница со скидкой",
"Whosale discounted": "Опт со скидкой",
"Goods id": "ID товара",
"Remove": "Удалить",
"Set retail price of selected goods": "Задать розничную цену выбранным товарам",
"Set whosale price of selected goods": "Задать оптовую цену выбранным товарам",
"Edit name": "Изменить название",
"Group discount": "Скидка группы",
"Group already added": "Группа уже добавлена",
"Select group of goods": "Выберите группу товаров",
"Confirm": "Подтвердить",
"New name": "Новое название",
"Confirm to remove": "Подтвердите удаление",
"Pricing options": "Параметры ценообразования",
"Round value": "Округление",
"Goods special whosale price": "Спец. оптовая цена товара",
"Partner Name": "Название контрагента",
"Parnert ID": "ID контрагента",
"Goods barcode": "Штрихкод товара",
"Partner addres": "Адрес контрагента",
"Goods special price": "Спец. цена товара",
"Goods special retail price": "Спец. розничная цена товара",
"Partner TIN": "ИНН контрагента",
"Goods ID": "ID товара",
"Goods group": "Группа товаров",
"Partner ID": "ID контрагента",
"Spesial price": "Спец. цена",
"Diff retail": "Разница розница",
"Diff whosale": "Разница опт",
"TaxCode": "ИНН",
"Empty report!": "Пустой отчёт!",
"Copy selection": "Копировать выделение",
"Copy all": "Копировать всё",
"Set filter": "Установить фильтр",
"Remove filter": "Снять фильтр",
"Autofit columns widths": "Автоширина столбцов",
"Report parameters": "Параметры отчёта",
"Parameters": "Параметры",
"Show columns": "Показать столбцы",
"Apply": "Применить",
"Actions": "Действия",
"All actions": "Все действия",
"Goods pricing": "Ценообразование товаров",
"Store input": "Приход на склад",
"Store movement": "Перемещение",
"Store output": "Расход со склада",
"Allow change store document date": "Разрешить менять дату складского документа",
"Goods reservatoins": "Резервы товаров",
"Retail sale": "Розничная продажа",
"Allow change cash document date": "Разрешить менять дату кассового документа",
"Store complectation": "Комплектация",
"Store inventory": "Инвентаризация",
"Calculate dishes self cost": "Расчёт себестоимости блюд",
"Whosale sale": "Оптовая продажа",
"All items": "Все позиции",
"Show sales of all users": "Показывать продажи всех пользователей",
"Edit stoplist": "Редактировать стоп-лист",
"Print precheck": "Печать пречека",
"Quantity reminder": "Напоминание о количестве",
"Auto waste": "Автосписание",
"Complectations": "Комплектации",
"Classes": "Классы",
"Images": "Изображения",
"Units": "Ед. изм.",
"Storages": "Склады",
"Only price edit": "Только изменение цены",
"Groups": "Группы",
"Reports": "Отчёты",
"Sales, expert mode": "Продажи, экспертный режим",
"Sales from store": "Продажи со склада",
"Documents": "Документы",
"Goods consuption, draft": "Расход товаров, черновик",
"Detailed movement in the storage": "Детальное движение по складу",
"Debts to partners": "Долги контрагентам",
"Sales, removed dishes": "Продажи, удалённые блюда",
"Custom reports": "Пользовательские отчёты",
"Documents in the store": "Документы склада",
"Storage uncomplected": "Склад без комплектации",
"Discount statistics": "Статистика скидок",
"Goods movement": "Движение товаров",
"T-store extra": "T-склад доп.",
"Goods movement, uncomplected": "Движение товаров без комплектации",
"Storage": "Склад",
"Preorders": "Предзаказы",
"Sales, car visits": "Продажи, автовизиты",
"Sales, dishes": "Продажи, блюда",
"Reason for consuption": "Причина расхода",
"Goods output by calculation and sales": "Расход товаров по расчёту и продажам",
"Salary": "Зарплата",
"Edit document": "Редактировать документ",
"Report": "Отчёт",
"Payment": "Оплата",
"Cash": "Касса",
"Cash common report": "Общий кассовый отчёт",
"Cash names": "Названия касс",
"Movement in the cash": "Движение по кассе",
"Cash detailed report": "Детальный кассовый отчёт",
"Costumer debts report": "Отчёт по долгам клиентов",
"Costumer debts pay": "Погашение долгов клиентов",
"Edit cash documents": "Редактирование кассовых документов",
"Edit currency rate": "Редактирование курса валют",
"Cash shifts": "Кассовые смены",
"Dish price and self cost report": "Отчёт: цена и себестоимость блюд",
"Dish remove reasons": "Причины удаления блюд",
"Menu names": "Названия меню",
"Types of dishes": "Типы блюд",
"Dish departments": "Отделы блюд",
"Review menu": "Обзор меню",
"Dishes packages": "Пакеты блюд",
"Waiter": "Официант",
"Edit orders": "Редактирование заказов",
"Reprint precheck": "Повторная печать пречека",
"Cancel precheck": "Отмена пречека",
"Special payment types": "Особые типы оплаты",
"Close order": "Закрыть заказ",
"Remove printed goods": "Удалить распечатанные товары",
"Reprint printed goods": "Повторная печать товаров",
"Transfer items": "Перенос позиций",
"Change service factor": "Изменить сервисный коэффициент",
"Remove discount": "Снять скидку",
"Open close shift": "Открытие/закрытие смены",
"Shop": "Магазин",
"Enter to sales": "Перейти к продажам",
"Enter to storages deals": "Перейти к складским операциям",
"Fiscal report": "Фискальный отчёт",
"Report, by goods": "Отчёт по товарам",
"Report, by groups of goods": "Отчёт по группам товаров",
"Refund goods": "Возврат товаров",
"Delete row from order": "Удалить строку из заказа",
"Discount": "Скидка",
"Other": "Прочее",
"Partners": "Контрагенты",
"Credit cards": "Банковские карты",
"Halls": "Залы",
"Tables": "Столы",
"Discount system": "Система скидок",
"Upload data to other server": "Выгрузка данных на другой сервер",
"Settings for data synchronization": "Настройки синхронизации данных",
"Store reasons": "Причины склада",
"Order marks": "Метки заказов",
"Route": "Маршрут",
"Route exec": "Выполнение маршрута",
"Preferences": "Параметры",
"Login to manager": "Вход менеджера",
"Login to waiter": "Вход официанта",
"Users groups": "Группы пользователей",
"Users": "Пользователи",
"Databases": "Базы данных",
"Settings": "Настройки",
"Manufacture": "Производство",
"Menu availbility": "Доступность меню",
"Workshops list": "Список цехов",
"Process stages": "Этапы процессов",
"Product list": "Список изделий",
"Action list": "Список действий",
"Daily processes": "Дневные процессы",
"General report": "Общий отчёт",
"General report only date": "Общий отчёт только по дате",
"Edit tasks": "Редактирование заданий",
"List of active tasks": "Список активных заданий",
"Miscellaneous": "Разное",
"Permissions": "Права доступа",
"Shift": "Смена",
"Shift was not selected": "Смена не выбрана",
"Username": "Пользователь",
"Password": "Пароль",
"Database": "База данных",
"Storehouse": "Склад",
"Navigation": "Навигация",
"Close application": "Закрыть приложение",
"Logout": "Выход",
"Disconnected": "Отключено",
}
