# -*- coding: utf-8 -*-
"""Part 3 of professional RU translations for FrontDesk."""
T = {
"Failed to send the reload request. Check the connection to the server.": "Не удалось отправить запрос перезагрузки. Проверьте связь с сервером.",
"Update": "Обновить",
"English (key)": "Английский (ключ)",
"Armenian": "Армянский",
"Russian": "Русский",
"You have not permission": "Недостаточно прав",
"Edit": "Изменить",
"changes": "изменения",
"Search by": "Поиск по",
"parameters": "параметры",
"Clear": "Очистить",
"Export to": "Экспорт в",
"MS Excel": "MS Excel",
"Create tables for hall": "Создать столы для зала",
"Prefix": "Префикс",
"First": "Первый",
"Count": "Количество",
"Create": "Создать",
"Hall is not selected": "Зал не выбран",
"Load image": "Загрузить изображение",
"Select image": "Выбрать изображение",
"Credit card": "Банковская карта",
"Base currency": "Базовая валюта",
"Dependened currency": "Зависимая валюта",
"Cross currency rate": "Кросс-курс валют",
"Currency 1": "Валюта 1",
"Currency 2": "Валюта 2",
"Set current rate": "Установить текущий курс",
"Cross rate": "Кросс-курс",
"Currency rate": "Курс валюты",
"Active": "Активен",
"Client": "Клиент",
"Value": "Значение",
"Discount type": "Тип скидки",
"Card number": "Номер карты",
"Card code": "Код карты",
"Discount card": "Дисконтная карта",
"Duplicate card code": "Дубликат кода карты",
"Dishes": "Блюда",
"Self cost": "Себестоимость",
"Printer": "Принтер",
"Selfcost": "Себестоимость",
"Enabled": "Включено",
"Dish package": "Пакет блюд",
"Storage not selected": "Склад не выбран",
"The quantity of dishes must be greater then zero.": "Количество блюд должно быть больше нуля.",
"Append": "Добавить",
"Image UUID": "UUID изображения",
"Dish department": "Отдел блюд",
"Right click to select image": "ПКМ для выбора изображения",
"You should to save before upload an image": "Сначала сохраните, затем загрузите изображение",
"ADG code": "Код АДГ",
"Department": "Отдел",
"Parent": "Родитель",
"Qr Required": "Требуется QR",
"ՀԴՄ բաժին": "Отдел ККМ",
"Չփոխել չափսը": "Не менять размер",
"Dish type": "Тип блюда",
"Cannot parent itself": "Нельзя сделать родителем самого себя",
"Dish remove reason": "Причина удаления блюда",
"Program error. Cannot find field with id property": "Ошибка программы. Не найдено поле со свойством id",
"Invalid code": "Неверный код",
"Duplicate id": "Дубликат ID",
"cannot be empty": "не может быть пустым",
"Margin 2": "Наценка 2",
"Margin 1": "Наценка 1",
"Low level": "Минимальный остаток",
"Weight": "Вес",
"Account": "Счёт",
"Cost price": "Себестоимость",
"Pricing": "Ценообразование",
"Production": "Производство",
"No price modificator": "Без модификатора цены",
"Հդմ անվանում": "Наименование ККМ",
"Box quantity": "Кол-во в коробке",
"Count service": "Учитывать сервис",
"Count discount": "Учитывать скидку",
"Ready output": "Готовый выход",
"unit": "ед. изм.",
"Row id": "ID строки",
"Attributes": "Атрибуты",
"Dietary / Allergen Badges": "Диета / аллергены",
"Gluten-free": "Без глютена",
"Vegetarian": "Вегетарианское",
"Vegan": "Веганское",
"No GMO": "Без ГМО",
"Lactose-free": "Без лактозы",
"Sugar-free": "Без сахара",
"Contains nuts": "Содержит орехи",
"Halal / Kosher": "Халяль / Кошер",
"Macros / Nutrition (per 100 g)": "БЖУ / пищевая ценность (на 100 г)",
"Calories, kcal": "Калории, ккал",
"Protein, g": "Белки, г",
"Fat, g": "Жиры, г",
"Carbs, g": "Углеводы, г",
"Dynamic attributes": "Динамические атрибуты",
"Attribute": "Атрибут",
"Measurement": "Измерение",
"Modificators": "Модификаторы",
"Modificator name": "Название модификатора",
"Required": "Обязательно",
"Relations": "Связи",
"Drinks": "Напитки",
"Others": "Прочее",
"Component exit": "Выход компонента",
"Options": "Параметры",
"Same store id": "Тот же ID склада",
"Web link": "Веб-ссылка",
"Gen barcode EAN8": "Сгенерировать штрихкод EAN8",
"Queue in list": "Очередь в списке",
"Fixed value": "Фиксированное значение",
"Percent value": "Процентное значение",
"Store output goods": "Товары расхода склада",
"Only whole number": "Только целое число",
"Sale price": "Цена продажи",
"Retail disc": "Скидка розница",
"Whosale disc": "Скидка опт",
"Duplicate scancode": "Дубликат штрихкода",
"Goods code for store output cannot be undefined": "Код товара для расхода не может быть пустым",
"Goods type must be selected": "Выберите тип товара",
"Print card": "Печать карточки",
"Template not found": "Шаблон не найден",
"Printed": "Напечатано",
"Goods card": "Карточка товара",
"Internal code": "Внутренний код",
"Price type": "Тип цены",
"Complectation cost": "Себестоимость комплектации",
"Could not encode image": "Не удалось закодировать изображение",
"Scancode field must be empty": "Поле штрихкода должно быть пустым",
"Clear current data": "Очистить текущие данные",
"This modificator is already added": "Этот модификатор уже добавлен",
"This dish is already added": "Это блюдо уже добавлено",
"Tax dept": "Налоговый отдел",
"Charge value": "Наценка",
"Class": "Класс",
"Model": "Модель",
"Default qty for shop": "Кол-во по умолчанию для магазина",
"Full name": "Полное имя",
"Goods unit": "Ед. изм. товара",
"Hall of counter": "Зал стойки",
"Counter": "Стойка",
"Order prefix": "Префикс заказа",
"Default settings": "Настройки по умолчанию",
"Stage": "Этап",
"Actions stage": "Этап действий",
"Հիմնական": "Основное",
"Update prices": "Обновить цены",
"Չափումներ": "Измерения",
"Անվանում": "Наименование",
"Արժեք": "Значение",
"Լրացուցիչ": "Дополнительно",
"Նկար": "Изображение",
"Նյութածախս": "Расход материалов",
"Կոդ": "Код",
"Քանակ": "Количество",
"Կտորի բաղադրություն": "Состав изделия",
"Սպիտակեցումը հակացուցված է": "Отбеливание противопоказано",
"Չոր մաքրում": "Химчистка",
"Հարդուկ": "Глажка",
"Լվացում": "Стирка",
"Չքամել և չչորացնել լվացքի մեքենայում": "Не отжимать и не сушить в стиральной машине",
"Ընդացիկ առաջադրանքներ": "Текущие задания",
"Rownum": "№",
"Duration, sec": "Длительность, сек",
"7h goal": "Цель 7ч",
"Goal price": "Целевая цена",
"Update price": "Обновить цену",
"Done.": "Готово.",
"Save first": "Сначала сохраните",
"Confirm to clear whole process": "Подтвердите очистку всего процесса",
"Do you want to create complectation documents?": "Создать документы комплектации?",
"Created": "Создано",
"Main info": "Основная информация",
"Workshop": "Цех",
"Ready": "Готово",
"Out": "Выход",
"Date create": "Дата создания",
"Responsible": "Ответственный",
"Notes": "Заметки",
"Key": "Ключ",
"Task": "Задание",
"Length": "Длина",
"Width": "Ширина",
"Size": "Размер",
"Start date": "Дата начала",
"End date": "Дата окончания",
"Duplicate name": "Дубликат названия",
"Order mark": "Метка заказа",
"Package": "Пакет",
"Sum of components": "Сумма компонентов",
"Package price": "Цена пакета",
"Sale type": "Тип продажи",
"Category": "Категория",
"Legal Address": "Юридический адрес",
"Manager": "Менеджер",
"Taxpayer id": "ИНН",
"Select category": "Выберите категорию",
"Select group": "Выберите группу",
"Select state": "Выберите состояние",
"Output counter": "Счётчик расхода",
"Complectation counter": "Счётчик комплектации",
"Movement counter": "Счётчик перемещения",
"Input counter": "Счётчик прихода",
"Movement reason": "Причина перемещения",
"This item is not editable": "Эту запись нельзя редактировать",
"Special config": "Особая конфигурация",
"Hourly fee id": "ID почасовой ставки",
"Table": "Стол",
"Photo": "Фото",
"Last name": "Фамилия",
"First name": "Имя",
"Configuration": "Конфигурация",
"Duplicate login name": "Дубликат логина",
"Fine per minute": "Штраф за минуту",
"Work start time": "Начало работы",
"Department code": "Код отдела",
"Maximum fine minute": "Макс. минут штрафа",
"Work end time": "Окончание работы",
"Skip amount": "Пропускаемая сумма",
"Count only working time": "Учитывать только рабочее время",
"Minimum": "Минимум",
"Maximum": "Максимум",
"User group": "Группа пользователей",
"Car visits": "Автовизиты",
"Gov number": "Госномер",
"Bank": "Банк",
"Column &apos;Header&apos; must be checked in filter": "В фильтре должен быть отмечен столбец «Header»",
"Nothing selected": "Ничего не выбрано",
"Costumer": "Клиент",
"Gov. number": "Госномер",
"Purpose": "Назначение",
"Cashdesk": "Касса",
"Tax": "Налог",
"All": "Все",
"Complimentary": "Комплиментарный",
"Not complimentary": "Не комплиментарный",
"Yes": "Да",
"No": "Нет",
"Returned item": "Возвращённая позиция",
"Hotel": "Гостиница",
"Date cash is null": "Дата кассы пуста",
"With buyer": "С покупателем",
"Use closing": "Использовать закрытие",
"datetime": "дата/время",
"Staff": "Персонал",
"Report type": "Тип отчёта",
"Quantities": "Количества",
"Amounts": "Суммы",
"Sale counted": "Продажа учтена",
"Qty, recipe": "Кол-во, рецепт",
"Qty, sale": "Кол-во, продажа",
"Dish part": "Часть блюда",
"Currencies": "Валюты",
"Cross rates": "Кросс-курсы",
"Name 1": "Название 1",
"Name 2": "Название 2",
"Cross rates history": "История кросс-курсов",
"Currency code 1": "Код валюты 1",
"Currency rates history": "История курсов валют",
"Host": "Хост",
"Access": "Доступ",
"Backup": "Резервная копия",
"database": "база данных",
"Reset": "Сброс",
"Select folder for dump": "Выберите папку для дампа",
"Backup with error": "Резервное копирование с ошибкой",
"Backup completed": "Резервное копирование завершено",
"Dicount system": "Система скидок",
"Mode": "Режим",
"Contact name": "Контактное лицо",
"Client info": "Информация о клиенте",
"Dept name": "Название отдела",
"This name in use and cannot be removed": "Это имя используется и не может быть удалено",
"Confirm to remove the selected dish part and all dishes that includes this part": "Подтвердите удаление выбранной части блюда и всех блюд, которые её содержат",
"Document type": "Тип документа",
"Reason*": "Причина*",
"*Only for documents in the store": "*Только для складских документов",
"Document state": "Состояние документа",
"Supplier": "Поставщик",
"Paid": "Оплачено",
"Operator": "Оператор",
"Type of dish": "Тип блюда",
"Type of goods": "Тип товара",
"Manufacture general report only date": "Общий отчёт производства только по дате",
"Worker": "Работник",
"Counted": "Учтено",
"Days": "Дни",
"Average": "Среднее",
"Absent": "Отсутствует",
"Image size": "Размер изображения",
"Real charge value": "Фактическая наценка",
"Fiscal name": "Фискальное наименование",
"Build web": "Сборка веб",
"Group price": "Цена группы",
"Scales": "Весы",
"ArmSoft map": "Сопоставление ArmSoft",
"S/R price update": "Обновление цен S/R",
"ID Column must be included in report": "В отчёт должен быть включён столбец ID",
"Warning! This operation will applied to all goods in the current report! Continue?": "Внимание! Операция будет применена ко всем товарам текущего отчёта! Продолжить?",
"You must select Code field in the report": "В отчёте нужно выбрать поле «Код»",
"You must select Last Input field in the report": "В отчёте нужно выбрать поле «Последний приход»",
"You must select Charge value field in the report": "В отчёте нужно выбрать поле «Наценка»",
"Used in recipes": "Используется в рецептах",
"Used in complectation": "Используется в комплектации",
"Used in store documents": "Используется в складских документах",
"Used in sales (shop)": "Используется в продажах (магазин)",
"Cannot remove ": "Нельзя удалить ",
"Select currency": "Выберите валюту",
"Build complete": "Сборка завершена",
"Last input price": "Цена последнего прихода",
"No service": "Без сервиса",
"Price currency": "Валюта цены",
"Group of goods": "Группа товаров",
"Delete selected goods group?": "Удалить выбранную группу товаров?",
"Group contains %1 goods. Move them to another group and delete?": "В группе %1 товаров. Переместить в другую группу и удалить?",
"Select another group": "Выберите другую группу",
"Reason": "Причина",
"Group of material": "Группа материалов",
"In/Out": "Приход/Расход",
"Store, input": "Склад, приход",
"Store. output": "Склад, расход",
"Material": "Материал",
"Legal address": "Юридический адрес",
"Low quantity": "Низкий остаток",
"Min qty": "Мин. кол-во",
"Material group": "Группа материалов",
"Goods reservation": "Резерв товара",
"Source": "Источник",
"Message": "Сообщение",
"Search date": "Дата поиска",
"Show current reserves": "Показать текущие резервы",
"Date created": "Дата создания",
"Date expired": "Дата окончания",
"Date completed": "Дата завершения",
"Date canceled": "Дата отмены",
"Default qty": "Кол-во по умолчанию",
"Hall counter": "Счётчик зала",
"Stages of actions": "Этапы действий",
"Tasks": "Задания",
"Configure": "Настроить",
"tablet": "планшет",
"Manufacture general report": "Общий отчёт производства",
"Worker state": "Состояние работника",
"Worker position": "Должность работника",
"Show zeroes": "Показывать нули",
"Show drafts": "Показывать черновики",
"Materials in the store without complects": "Материалы на складе без комплектов",
"Total retail": "Итого розница",
"Total whosale": "Итого опт",
"Unit of complected goods must be defined": "Укажите ед. изм. комплектуемого товара",
"Class 3": "Класс 3",
"Class 4": "Класс 4",
"Class 1": "Класс 1",
"Class 2": "Класс 2",
"Unit of complect": "Ед. изм. комплекта",
"VIew": "Просмотр",
"Storage movement, uncomplect": "Перемещение без комплектации",
"Action": "Действие",
"Materials in the store": "Материалы на складе",
"Warning": "Внимание",
"Retail amount": "Сумма розница",
"Total retail discounted": "Итого розница со скидкой",
"Total whosale discounted": "Итого опт со скидкой",
"Whosale amount": "Сумма опт",
"Code column must be included in report": "В отчёт должен быть включён столбец «Код»",
"No recipe": "Без рецепта",
"English": "Английский",
"Manufacture actions": "Действия производства",
"Stage code": "Код этапа",
"find employee": "найти сотрудника",
"Daily journal": "Дневной журнал",
"Max": "Макс.",
"Process id": "ID процесса",
"Last": "Последний",
"work": "работа",
"action": "действие",
"all workers": "все работники",
"Could not add task": "Не удалось добавить задание",
"No active task": "Нет активного задания",
"Saved, but some of quantities equals to 0.": "Сохранено, но часть количеств равна 0.",
"The quantity of the processes is greater than goal": "Количество процессов больше цели",
"user": "пользователь",
"Worker already added in selected date": "Работник уже добавлен на выбранную дату",
"Are you sure to remove?": "Удалить?",
"Worker is not selected": "Работник не выбран",
"Orders marks": "Метки заказов",
"Preorders history": "История предзаказов",
"Time created": "Время создания",
"Date for": "Дата на",
"Time for": "Время на",
"Advance": "Аванс",
"Invalid report id": "Неверный ID отчёта",
"Confirm to remove selected objects": "Подтвердите удаление выбранных объектов",
"Crossrate": "Кросс-курс",
"Edit route": "Редактировать маршрут",
"Salary by workers": "Зарплата по работникам",
"Employee": "Сотрудник",
"Display": "Отображение",
"Without fiscal": "Без фискального",
"With fiscal": "С фискальным",
}
