# -*- coding: utf-8 -*-
"""Part 4 of professional RU translations for FrontDesk."""
T = {
"Goods type": "Тип товара",
"Returned items": "Возвращённые позиции",
"Sales from store total": "Продажи со склада, итог",
"Initial": "Начальный",
"Final, qty": "Конечное кол-во",
"Final amount": "Конечная сумма",
"Show quantity": "Показать количество",
"Show amount": "Показать сумму",
"Header": "Заголовок",
"Order state": "Состояние заказа",
"Date, cash": "Дата, касса",
"Time, close": "Время закрытия",
"Dept": "Отдел",
"Dish state": "Состояние блюда",
"Remove reason": "Причина удаления",
"Column &apos;Dish code&apos; must be checked in filter": "В фильтре должен быть отмечен столбец «Код блюда»",
"With recipe": "С рецептом",
"Delete": "Удалить",
"settings": "настройки",
"Confirm removal": "Подтвердите удаление",
"Partial": "Частичный",
"Store move reason": "Причина перемещения",
"Store price": "Складская цена",
"Retail prices": "Розничные цены",
"Input prices": "Цены прихода",
"Create hall": "Создать зал",
"Cannot delete default table": "Нельзя удалить стол по умолчанию",
"Delete selected table?": "Удалить выбранный стол?",
"Config": "Конфигурация",
"passwords": "пароли",
"Set group": "Задать группу",
"permissions": "права",
"Calculator": "Калькулятор",
"Calendar": "Календарь",
"Received": "Получено",
"Phone number": "Номер телефона",
"Customer name": "Имя клиента",
"Address must be defined": "Укажите адрес",
"Phone must defined": "Укажите телефон",
"Invalid phone number": "Неверный номер телефона",
"Waiter workstation": "Рабочее место официанта",
"Money in/out": "Внесение/изъятие",
"Amount cannot be zero": "Сумма не может быть нулевой",
"Purpose must be defined": "Укажите назначение",
"Close session": "Закрыть смену",
"Current balance:": "Текущий баланс:",
"Input from sale": "Приход от продажи",
"Cash amount": "Сумма наличных",
"Input from delivery": "Приход от доставки",
"Incorrect balance": "Неверный баланс",
"Confirm to close session": "Подтвердите закрытие смены",
"Including:": "В том числе:",
"Other transactions": "Прочие операции",
"Total balance": "Общий баланс",
"Avaiable cash": "Доступные наличные",
"Change the store of oupput": "Изменить склад расхода",
"Change the store": "Изменить склад",
"Check visible": "Проверить видимость",
"Store is not selected": "Склад не выбран",
"Are you sure to change store?": "Изменить склад?",
"Redeem debt": "Погасить долг",
"Supplier debt (we owe)": "Долг поставщику (мы должны)",
"Customer debt (they owe us)": "Долг клиента (нам должны)",
"Currency id": "ID валюты",
"Select partner": "Выберите контрагента",
"Document raw editor": "Редактор сырых данных документа",
"Used": "Использовано",
"Cannot remove goods that was used": "Нельзя удалить использованный товар",
"Confirm remove": "Подтвердите удаление",
"New quantity less than used": "Новое количество меньше использованного",
"Create route": "Создать маршрут",
"Select driver": "Выберите водителя",
"Export options": "Параметры экспорта",
"Service out account": "Счёт расхода услуг",
"Items in account": "Счёт прихода товаров",
"Partner code": "Код контрагента",
"Store code": "Код склада",
"VAT value": "Ставка НДС",
"Items out account": "Счёт расхода товаров",
"Export simple": "Простой экспорт",
"Service in account": "Счёт прихода услуг",
"No tax": "Без налога",
"Bank acquiring account": "Счёт эквайринга",
"Service item": "Сервисная позиция",
"Simple  item": "Простая позиция",
"Guest info": "Данные гостя",
"Search customer": "Поиск клиента",
"Enter name or phone (min 2 characters)": "Введите имя или телефон (мин. 2 символа)",
"Connection success": "Подключение успешно",
"Connection error": "Ошибка подключения",
"Inventory blanks": "Бланки инвентаризации",
"Select a blank": "Выберите бланк",
"Delete selected blank?": "Удалить выбранный бланк?",
"Compare with recipes": "Сравнить с рецептами",
"No longer in recipes": "Больше нет в рецептах",
"No longer in recipes (%1)": "Больше нет в рецептах (%1)",
"New in recipes": "Новое в рецептах",
"New in recipes (%1)": "Новое в рецептах (%1)",
"Apply all": "Применить всё",
"Remove obsolete": "Удалить устаревшие",
"Add new": "Добавить новые",
"Inventory blank": "Бланк инвентаризации",
"Title": "Название",
"SKU": "Артикул",
"Add row": "Добавить строку",
"Refresh from recipes": "Обновить из рецептов",
"Enter title": "Введите название",
"Blank matches recipes": "Бланк соответствует рецептам",
"Select store": "Выберите склад",
"Create blank for which store?": "Для какого склада создать бланк?",
"All stores (one common blank)": "Все склады (один общий бланк)",
"Store #%1": "Склад №%1",
"Comment for": "Комментарий для",
"New cityledger": "Новый городской журнал",
"The name cannot be empty": "Наименование не может быть пустым",
"TABLE": "СТОЛ",
"Remove from stoplist": "Убрать из стоп-листа",
"Enter your username and pin": "Введите имя пользователя и PIN",
"Set quantity": "Указать количество",
"Reserve number": "Номер резерва",
"Reserved qty": "Зарезервировано",
"Reserve date": "Дата резерва",
"Available qty": "Доступно",
"ՀԴՄ Կ/Տ": "ККМ К/Б",
"Կանխիկ": "Наличные",
"Cancel reserve": "Отменить резерв",
"Complete reserve": "Завершить резерв",
"Անկանխիկ": "Безнал",
"Day of end": "День окончания",
"Goods is not specified": "Товар не указан",
"Store is not specified": "Склад не указан",
"The end date is not valid": "Дата окончания некорректна",
"The end date can be tomorrow": "Дата окончания может быть завтра",
"Incorrect quantity": "Некорректное количество",
"Insufficient quantity": "Недостаточное количество",
"Fiscal check printed successfully": "Фискальный чек успешно напечатан",
"Sales amount": "Сумма продаж",
"Percent": "Процент",
"Accrual": "Начисление",
"Summary": "Итог",
"Loading...": "Загрузка...",
"Employee or position is not set.": "Сотрудник или должность не указаны.",
"Date: %1, employee: %2": "Дата: %1, сотрудник: %2",
"Sales total: %1": "Итого продаж: %1",
"After skip amount (%1): %2": "После пропускаемой суммы (%1): %2",
"Divided by employees with same position: %1": "Разделено между сотрудниками с той же должностью: %1",
"Dish sales base: %1": "База продаж блюд: %1",
"No percent-based dish sales found for this employee on the selected date.": "Нет процентных продаж блюд для этого сотрудника на выбранную дату.",
"Semiready goods": "Полуфабрикаты",
"Edit service value": "Изменить сервисный сбор",
"New service value": "Новый сервисный сбор",
"Delete selected service value?": "Удалить выбранный сервисный сбор?",
"New City ledger": "Новый городской журнал",
"Text": "Текст",
"Prepare to work": "Подготовка к работе",
"Saved payment variants": "Сохранённые варианты оплаты",
"Variant": "Вариант",
"Currency not selected": "Валюта не выбрана",
"Delete selected payment variant?": "Удалить выбранный вариант оплаты?",
"Price deviation warning": "Предупреждение об отклонении цены",
"Warning mode": "Режим предупреждения",
"Do not warn": "Не предупреждать",
"Warn before save": "Предупреждать перед сохранением",
"Warn after price edit (focus lost)": "Предупреждать после изменения цены (потеря фокуса)",
"Deviation percent": "Процент отклонения",
"Match goods": "Сопоставить товары",
"Some goods were not found by name. Match each line to a goods item or create a new one.": "Некоторые товары не найдены по названию. Сопоставьте каждую строку с товаром или создайте новый.",
"Import name": "Название из импорта",
"Goods in database": "Товар в базе",
"Update name": "Обновить название",
"Rename": "Переименовать",
"Match or create all goods before import. Row: %1": "Сопоставьте или создайте все товары перед импортом. Строка: %1",
"XML import options": "Параметры импорта XML",
"Choose how to handle partners, goods and duplicate invoices during import.": "Выберите, как обрабатывать контрагентов, товары и дубликаты накладных при импорте.",
"Select input store": "Выберите склад прихода",
"Open documents in windows (do not save automatically)": "Открыть документы в окнах (не сохранять автоматически)",
"Save immediately as draft (do not open windows)": "Сразу сохранить как черновик (не открывать окна)",
"Save immediately fully / posted (do not open windows)": "Сразу сохранить проведённым (не открывать окна)",
"Save immediately as draft (do not open documents in windows)": "Сразу сохранить как черновик (не открывать документы в окнах)",
"Partner not found": "Контрагент не найден",
"Create partner automatically from invoice data": "Создать контрагента автоматически по данным накладной",
"Do not create — abort import of this invoice": "Не создавать — прервать импорт этой накладной",
"Goods not found": "Товар не найден",
"Create goods automatically": "Создать товар автоматически",
"Open match dialog (map or create manually)": "Открыть диалог сопоставления (вручную)",
"Duplicates (Series + Number)": "Дубликаты (серия + номер)",
"Overwrite — delete all found documents, then import one new": "Перезаписать — удалить найденные документы, затем импортировать новый",
"Skip — do not import duplicate invoices": "Пропустить — не импортировать дубликаты",
"Cancel — abort entire import if any duplicate is found": "Отмена — прервать весь импорт при любом дубликате",
"Select invoices": "Выберите накладные",
"Check invoices to import. The first checked one is imported into the current document; the others open in new windows. Double-click a row to preview invoice lines.": "Отметьте накладные для импорта. Первая отмеченная импортируется в текущий документ; остальные откроются в новых окнах. Двойной клик — просмотр строк.",
"Select all": "Выбрать все",
"Clear all": "Очистить все",
"TIN": "ИНН",
"Invoice #": "Накладная №",
"Check at least one invoice": "Отметьте хотя бы одну накладную",
"Invoice preview": "Просмотр накладной",
"Invoice preview — %1": "Просмотр накладной — %1",
"Invoice: %1": "Накладная: %1",
"Supplier: %2": "Поставщик: %2",
"TIN: %3": "ИНН: %3",
"Date: %4": "Дата: %4",
"Total: %5": "Итого: %5",
"Lines: %6": "Строк: %6",
"Update partner data": "Обновить данные контрагента",
"Partner data differs from invoice. Select fields to update.": "Данные контрагента отличаются от накладной. Выберите поля для обновления.",
"Field": "Поле",
"In database": "В базе",
"In invoice": "В накладной",
"Tax name": "Налоговое наименование",
"Select at least one field to update": "Выберите хотя бы одно поле для обновления",
"No fingerprint registered": "Отпечаток не зарегистрирован",
"Register fingerprint": "Зарегистрировать отпечаток",
"Fingerprint is registered": "Отпечаток зарегистрирован",
"Replace fingerprint": "Заменить отпечаток",
"Fingerprint saved": "Отпечаток сохранён",
"Waiting for scanner...": "Ожидание сканера...",
"Remove fingerprint for this user?": "Удалить отпечаток этого пользователя?",
"Fingerprint removed": "Отпечаток удалён",
"Please, wait...": "Подождите...",
"Operation timeout": "Таймаут операции",
"Authorization error": "Ошибка авторизации",
"Application update required": "Требуется обновление приложения",
"Search parameters": "Параметры поиска",
"New customer payment": "Новый платёж клиента",
"New partner payment": "Новый платёж контрагента",
"Pay off a debt": "Погасить долг",
"Pay off a debt?": "Погасить долг?",
"Redeem accumulated": "Списать накопленное",
"Unauthorized": "Нет авторизации",
"1 sec": "1 сек",
"The message!": "Сообщение!",
"Tax code": "ИНН",
"Prepaid": "Предоплата",
"View": "Просмотр",
"Tax number": "Налоговый номер",
"Total advance": "Всего аванс",
"Failed to start sc.exe": "Не удалось запустить sc.exe",
"Service command timeout": "Таймаут команды службы",
"Failed to start PowerShell for elevation.": "Не удалось запустить PowerShell для повышения прав.",
"UAC request timeout.": "Таймаут запроса UAC.",
"Sale report": "Отчёт по продажам",
"System": "Система",
"Document status": "Статус документа",
"Employee group": "Группа сотрудников",
"Use the same finger for all scans": "Используйте один и тот же палец для всех сканирований",
"Registration restarted": "Регистрация перезапущена",
"Press finger %1 of %2": "Приложите палец %1 из %2",
"Failed to merge fingerprint templates": "Не удалось объединить шаблоны отпечатков",
"Verification: press the same finger again": "Проверка: приложите тот же палец ещё раз",
"Verification failed, try again": "Проверка не пройдена, попробуйте снова",
"Settings editor is not available for this workstation type": "Редактор настроек недоступен для этого типа рабочей станции",
"Reload": "Перезагрузить",
"Columns": "Столбцы",
"Do you want to delete the selected document?": "Удалить выбранный документ?",
"Select document type": "Выберите тип документа",
"No data to filter.": "Нет данных для фильтра.",
"Filter: %1": "Фильтр: %1",
"(empty)": "(пусто)",
"Save Excel": "Сохранить Excel",
"Could not save file": "Не удалось сохранить файл",
"movement": "перемещение",
"Recalculate": "Пересчитать",
"store output": "расход склада",
"Recalculate store output for the selected period?": "Пересчитать расход склада за выбранный период?",
"Existing write-offs will be removed and sales will be posted again.": "Существующие списания будут удалены, продажи будут проведены заново.",
"No closed sales found for the selected period": "За выбранный период нет закрытых продаж",
"Recalculating store output…": "Пересчёт расхода склада…",
"Processing %1 (%2 / %3)": "Обработка %1 (%2 / %3)",
"Request failed": "Запрос не выполнен",
"Failed": "Ошибка",
"Consumed goods — store output recalculation errors": "Израсходованные товары — ошибки пересчёта расхода",
"Done: %1 / %2": "Готово: %1 / %2",
"Select currency in parameters.": "Выберите валюту в параметрах.",
"Redemption recorded.": "Погашение записано.",
"Tab": "Tab",
"Switch to dishes and recipes mode": "Перейти в режим блюд и рецептов",
"Order not found": "Заказ не найден",
"Cash sessions": "Кассовые смены",
"Sold items": "Проданные позиции",
"Revenue": "Выручка",
"Session id": "ID смены",
"Closed": "Закрыта",
"Opened": "Открыта",
"Append time": "Время добавления",
"Print time": "Время печати",
"Remove time": "Время удаления",
"Important": "Важно",
"Cashier": "Кассир",
"Present card pattern": "Шаблон карты предъявления",
"Discount card pattern": "Шаблон дисконтной карты",
"Accumulate card pattern": "Шаблон накопительной карты",
"Scale pattern": "Шаблон весов",
"Quick debt partner id": "ID контрагента быстрого долга",
"Print server URL": "URL сервера печати",
"Input cashbox amount before close": "Вводить сумму кассы перед закрытием",
"Bistro mode": "Режим бистро",
"Auto fiscal": "Автофискализация",
"Print side margin (mm)": "Боковой отступ печати (мм)",
"Cashbox id": "ID кассы",
"Default hall id": "ID зала по умолчанию",
"Fiscal machine id": "ID фискального аппарата",
"Arcus server IP address": "IP-адрес сервера Arcus",
"Default store id": "ID склада по умолчанию",
"Card payment via arkus": "Оплата картой через Arcus",
"Port": "Порт",
"Arcus authorization": "Авторизация Arcus",
"API key": "API-ключ",
"Receipt phone": "Телефон на чеке",
"Receipt without table": "Чек без стола",
"Receipt without service hint": "Чек без подсказки сервиса",
"Receipt without discount hint": "Чек без подсказки скидки",
"Receipt policy": "Политика чека",
"Search menu horizontal section": "Горизонтальная секция поиска меню",
"Search menu vertical section": "Вертикальная секция поиска меню",
"Cost depended on service and discount": "Себестоимость зависит от сервиса и скидки",
"Precheck: phone and address only (no customer name)": "Пречек: только телефон и адрес (без имени клиента)",
"Recent dishes window (minutes)": "Окно недавних блюд (минуты)",
"Setup buttons (disable when checked)": "Кнопки настройки (отключить при отметке)",
"Disable button when checked": "Отключить кнопку при отметке",
"Station account": "Учётная запись станции",
"Settings editor is not available for workstation type %1": "Редактор настроек недоступен для типа рабочей станции %1",
"Workstations": "Рабочие станции",
"Service values": "Сервисные сборы",
"Select printers": "Выберите принтеры",
"Print #1": "Печать №1",
"Print #2": "Печать №2",
"Return": "Возврат",
"Device number": "Номер устройства",
"Serial": "Серийный номер",
"Receipt number": "Номер чека",
"(F)": "(Ф)",
"Buyer taxcode": "ИНН покупателя",
"Refund": "Возврат",
"Class | Name | Qty | Price | Total": "Класс | Название | Кол-во | Цена | Итого",
"Class:": "Класс:",
"Need to pay": "К оплате",
"Payment, cash": "Оплата, наличные",
"Payment, card": "Оплата, карта",
"Thank you for visit!": "Спасибо за визит!",
"Goods line without description": "Строка товара без описания",
"Invalid quantity for goods: %1": "Некорректное количество для товара: %1",
"Invalid TotalPrice for goods: %1": "Некорректная TotalPrice для товара: %1",
"Document id is empty": "ID документа пуст",
"Supplier TIN is missing": "ИНН поставщика отсутствует",
"Supply date is missing or invalid": "Дата поставки отсутствует или некорректна",
"Invoice has no goods lines": "В накладной нет строк товаров",
"Cannot open file: %1": "Не удалось открыть файл: %1",
"Invalid XML file": "Некорректный XML-файл",
"Invalid invoice data": "Некорректные данные накладной",
"XML parse error: %1": "Ошибка разбора XML: %1",
"User is not defined": "Пользователь не задан",
"Context is not defined": "Контекст не задан",
"Failed to create partner": "Не удалось создать контрагента",
"Empty goods description": "Пустое описание товара",
"Supplier is not defined": "Поставщик не задан",
"Failed to create goods": "Не удалось создать товар",
"Tax receipt number": "Номер фискального чека",
"Print tax X report": "Печать X-отчёта",
"Print tax Z report": "Печать Z-отчёта",
"Consumed goods": "Израсходованные товары",
"New sale": "Новая продажа",
"New store input": "Новый приход",
"New store output": "Новый расход",
"New store movement": "Новое перемещение",
"New store complectation": "Новая комплектация",
"Store moves": "Перемещения склада",
"New inventory": "Новая инвентаризация",
"Inventory documents": "Документы инвентаризации",
"City ledger": "Городской журнал",
"Order in progress": "Заказ в работе",
"Job titles": "Должности",
"Store documents": "Складские документы",
"Inventory": "Инвентаризация",
"Menu review": "Обзор меню",
"Dashboard buttons visibility": "Видимость кнопок панели",
"Select visible buttons": "Выберите видимые кнопки",
"Dish times": "Времена блюд",
"Event": "Событие",
"Cooking": "Приготовление",
"Served": "Подано",
"Status %1": "Статус %1",
"Dish id is missing": "ID блюда отсутствует",
"Not authorized": "Нет авторизации",
"Invalid time format on row \"%1\". Use yyyy-MM-dd HH:mm:ss": "Неверный формат времени в строке «%1». Используйте yyyy-MM-dd HH:mm:ss",
"Failed to save dish times": "Не удалось сохранить времена блюд",
"Order inspector": "Инспектор заказа",
"Click to copy order id": "Нажмите, чтобы скопировать ID заказа",
"Copy order id": "Копировать ID заказа",
"Removed": "Удалено",
"Kitchen": "Кухня",
"Component": "Компонент",
"Sold qty": "Продано",
"Consumed qty": "Израсходовано",
"Cost": "Себестоимость",
"Raw order": "Сырой заказ",
"Open": "Открыть",
"Empty": "Пусто",
"Moved": "Перемещено",
"Preorder": "Предзаказ",
"State %1": "Состояние %1",
"Failed to initialize fingerprint reader": "Не удалось инициализировать считыватель отпечатков",
"Failed to open fingerprint reader": "Не удалось открыть считыватель отпечатков",
"Failed to initialize fingerprint database": "Не удалось инициализировать базу отпечатков",
"Invalid fingerprint reader parameters": "Неверные параметры считывателя отпечатков",
"Fingerprint reader is not connected": "Считыватель отпечатков не подключён",
"Press finger 1 of %1": "Приложите палец 1 из %1",
"Place your finger on the scanner": "Приложите палец к сканеру",
"Fingerprint reader is supported on Windows only": "Считыватель отпечатков поддерживается только в Windows",
"About": "О программе",
"Restart Breeze": "Перезапустить Breeze",
"Version:": "Версия:",
"UAC confirmation requested. Breeze restart command was started as administrator.": "Запрошено подтверждение UAC. Команда перезапуска Breeze запущена от администратора.",
"Failed to request administrator restart for Breeze.": "Не удалось запросить перезапуск Breeze от администратора.",
"Elevation output:": "Вывод повышения прав:",
"Լավ": "ОК",
"Մաքրել": "Очистить",
"Ավելացնել": "Добавить",
"Հրաժարվել": "Отмена",
# Extra: strings that may be keep-as-is but should be translated when present
"Permanent discount": "Постоянная скидка",
"None": "Нет",
"Normal": "Обычный",
"Mistake": "Ошибка",
"Void": "Аннулирование",
"Extended": "Расширенный",
"Both": "Оба",
"Body": "Тело",
"In": "Приход",
"Flag 1": "Флаг 1",
"Flag 2": "Флаг 2",
"Flag 3": "Флаг 3",
"Flag 4": "Флаг 4",
"Flag 5": "Флаг 5",
"Flags": "Флаги",
"SalesCounted": "SalesCounted",
"Space": "Пробел",
"CAPS": "CAPS",
"Tab": "Tab",
}
