#include "version.h"

#define FILE_VERSION VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define FILE_VERSION_STR \
STR(VER_MAJOR) "." STR(VER_MINOR) "." STR(VER_PATCH) "." STR(VER_BUILD)
