#Requires -Version 5.1
param(
    [Parameter(Mandatory = $true)]
    [string]$Iscc,

    # frontdesk | shop | waiter | cookingprogress | service5 | all (default)
    [string]$Component = "all"
)

$ErrorActionPreference = "Stop"
$SetupDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$versionsPath = Join-Path $SetupDir "versions.json"
if (-not (Test-Path $versionsPath)) {
    throw "versions.json not found. Run stage.ps1 first."
}
$versions = Get-Content $versionsPath -Raw | ConvertFrom-Json

# Per-module close filter: only the module being installed/updated.
# Service5 keeps the legacy shared-folder behaviour (Breeze + all apps).
$PicassoCloseFilterAll = "OfficeN.exe,Shop_net.exe,Waiter.exe,WaiterDesigner.exe,CookingProgress.exe,service5.exe,Service5.exe,Updater.exe,PicassoUpdateHost.exe"

$allComponents = @(
    @{
        Key = "frontdesk"
        DisplayName = "FrontDesk"
        AppId = "{{A3F8C2E1-9B4D-4F6A-8C7E-1D2E3F4AFD01}"
        CloseFilter = "OfficeN.exe"
        Version = $versions.frontdesk
    }
    @{
        Key = "shop"
        DisplayName = "Shop"
        AppId = "{{A3F8C2E1-9B4D-4F6A-8C7E-1D2E3F4A5B01}"
        CloseFilter = "Shop_net.exe"
        Version = $versions.shop
    }
    @{
        Key = "waiter"
        DisplayName = "Waiter"
        AppId = "{{A3F8C2E1-9B4D-4F6A-8C7E-1D2E3F4A5C01}"
        CloseFilter = "Waiter.exe,WaiterDesigner.exe"
        Version = $versions.waiter
    }
    @{
        Key = "cookingprogress"
        DisplayName = "CookingProgress"
        AppId = "{{A3F8C2E1-9B4D-4F6A-8C7E-1D2E3F4A5E01}"
        CloseFilter = "CookingProgress.exe"
        Version = $versions.cookingprogress
    }
    @{
        Key = "service5"
        DisplayName = "Service5"
        AppId = "{{A3F8C2E1-9B4D-4F6A-8C7E-1D2E3F4A5D01}"
        CloseFilter = $PicassoCloseFilterAll
        Version = $versions.service5
    }
)

$Component = $Component.Trim().ToLowerInvariant()
if ($Component -eq "office" -or $Component -eq "officen") { $Component = "frontdesk" }

$components = if ($Component -eq "all") {
    $allComponents
} else {
    $hit = $allComponents | Where-Object { $_.Key -eq $Component }
    if (-not $hit) {
        throw "Unknown component '$Component'. Use: frontdesk, shop, waiter, cookingprogress, service5, all"
    }
    @($hit)
}

foreach ($c in $components) {
    $outName = "$($c.Key)_setup_$($c.Version)"
    $defines = @(
        "; Generated by build_components.ps1 - do not edit by hand"
        "#define ComponentKey `"$($c.Key)`""
        "#define ComponentDisplayName `"$($c.DisplayName)`""
        "#define ComponentAppId `"$($c.AppId)`""
        "#define ComponentOutputDir `"output\$($c.Key)`""
        "#define ComponentOutputName `"$outName`""
        "#define ComponentCloseFilter `"$($c.CloseFilter)`""
        "#define MyAppVersionShort `"$($c.Version)`""
    )
    $definesPath = Join-Path $SetupDir "component_defines.iss"
    Set-Content -Path $definesPath -Value $defines -Encoding ASCII

    Write-Host "Building $($c.Key) -> output\$($c.Key)\$outName.exe"
    & $Iscc (Join-Path $SetupDir "PicassoComponent.iss")
    if ($LASTEXITCODE -ne 0) {
        throw "ISCC failed for component $($c.Key)"
    }
}

Write-Host "Component installer(s) ready."
